### ISSUE TITLE
Test failed wrong output

### ISSUE THREAD

**Issue by dsmarcoantonio** [jsunfmi/SGZ#1] opened 2018-02-14 12:56 UTC
I am running Python 2.7.14 from Anaconda with scipy 1.0.0.
After runninf test: /usr/bin/python2 run_test.py I get several outputs like:
problem with EAF_sim:  301.0 0.148629655657
problem with EAF_sim:  319.0 0.2885
problem with EAF_sim:  312.0 0.174576970697
problem with EAF_sim:  327.0 0.523730912092
problem with EAF_sim:  256.0 0.5
problem with EAF_sim:  305.0 0.5
problem with EAF_sim:  423.0 0.351370344343
problem with EAF_sim:  132.0 0.587288485349
problem with EAF_sim:  394.0 0.523730912092
problem with EAF_sim:  337.0 0.587288485349
problem with EAF_sim:  491.0 0.423
Actual output file /data/software/SGZ/test_results/sample1.fmi.sgz.full.txt is different from expected output file /data/software/SGZ/test/expected_output/sample1.fmi.sgz.full.txt.

**Comment by ddesvillechabrol** [comment] 2018-03-01 15:10
Hello !
I am using Anaconda with:
- python 2.7.6
- numpy 1.14.1
- scipy 1.0.0

After running `run_test.py`, I have the same result than @dsmarcoantonio:
```
problem with EAF_sim:  301.0 0.148629655657
problem with EAF_sim:  319.0 0.2885
problem with EAF_sim:  312.0 0.174576970697
problem with EAF_sim:  327.0 0.523730912092
problem with EAF_sim:  256.0 0.5
problem with EAF_sim:  305.0 0.5
problem with EAF_sim:  423.0 0.351370344343
problem with EAF_sim:  132.0 0.587288485349
problem with EAF_sim:  394.0 0.523730912092
problem with EAF_sim:  337.0 0.587288485349
problem with EAF_sim:  491.0 0.423
Actual output file /bioinfo/users/ddesvill/chifumi/SGZ/test_results/sample1.fmi.sgz.full.txt is different from expected output file /bioinfo/users/ddesvill/chifumi/SGZ/test/expected_output/sample1.fmi.sgz.full.txt.
```

Best,
Dimitri

**Comment by yim6810** [comment] 2018-03-08 00:53
I also experience the same error message.  I use python 2.7 .6

**Comment by YutingH** [comment] 2018-03-16 15:19
@dsmarcoantonio @ddesvillechabrol @yim6810 

Thank you very much for your interest in this program. We have pushed a fix to the bug you have experienced, which was caused by the incompatibility between different versions of scipy.stats. As the binom.rvs function in the script is stochastic with a random seed set, we had to update the expected output file accordingly to accommodate the change to the random process by the bug fix.

**Comment by YutingH** [comment] 2018-03-16 15:20
Please feel free to email me at yhe@foundationmedicine.com if you have any further questions.

Best,
Yuting

**Closed as completed** 2018-03-16 15:28 UTC

**Comment by ddesvillechabrol** [comment] 2018-03-16 15:40
Thanks Yuting,

You should add a requirements file with versions of your packages.

Best,
Dimitri

**Comment by YutingH** [comment] 2018-03-16 17:32
@ddesvillechabrol 

Thank you very much, Dimitri for your suggestion. I have updated the README file to provide all the python module dependencies and their version info. 

Thanks,
Yuting
